services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=shark-ci
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_VOLUMES=/data
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - miniodata:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: minio server --console-address ":9001"

volumes:
  pgdata:
  miniodata:
