FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o bin/worker github.com/FilipSolich/shark-ci/cmd/worker


FROM alpine:latest

WORKDIR /

COPY --from=builder /app/bin/worker worker

CMD ["./worker"]
