services:
  ci-server:
    image: shark-ci/ci-server
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env
    environment:
      - DB_URI=postgres://shark-ci:shark-ci@postgres:5432/shark-ci?sslmode=disable
    ports:
      - "8000:8000"
    volumes:
      - ci-server:/var/lib/shark-ci
      - .env:/.env

  worker:
    image: shark-ci/worker
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .env:/.env

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=shark-ci
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

volumes:
  pgdata:
  ci-server:
