services:
  #ci-server:
  #  build: .
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - postgres
  #    - rabbitmq

  #postgres:
  #  image: postgres

  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
