FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o bin/ci-server github.com/shark-ci/shark-ci/cmd/ci-server


FROM alpine:latest

LABEL org.opencontainers.image.source=https://github.com/shark-ci/shark-ci

WORKDIR /

COPY --from=builder /app/bin/ci-server server
COPY ci-server/templates ci-server/templates

EXPOSE 8000

CMD ["./server"]
