FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o bin/ci-server github.com/FilipSolich/shark-ci/cmd/ci-server


FROM alpine:latest

WORKDIR /

COPY --from=builder /app/bin/ci-server /ci-server

CMD ["/ci-server"]
