version: '3'

vars:
  MODULE: github.com/shark-ci/shark-ci
  SERVER_IMAGE: shark-ci/server
  WORKER_IMAGE: shark-ci/worker
  DATETIME:
    sh: date --utc --rfc-3339=seconds
  VERSION:
    sh: git describe --tags --match 'v*' --abbrev=0 --always | sed 's/^v//'
  REVISION:
    sh: git rev-parse HEAD

dotenv: ['.env']

interval: '1s'

tasks:
  build:
    desc: Build CI server and worker
    aliases: ["b"]
    cmds:
      - task: build:server
      - task: build:worker

  build:server:
    desc: Build CI server
    cmds:
      - go build -o bin/server {{.MODULE}}/cmd/server
    sources:
      - cmd/server/*.go
      - internal/**/*.go
      - exclude: internal/worker/*
    generates:
      - bin/server
    method: timestamp

  build:worker:
    desc: Build worker
    cmds:
      - go build -o bin/worker {{.MODULE}}/cmd/worker
    sources:
      - cmd/worker/*.go
      - internal/**/*.go
      - exclude: internal/server/*
    generates:
      - bin/worker
    method: timestamp

  run:
    desc: Run CI server and worker
    aliases: ["r"]
    deps:
      - run:server
      - run:worker

  run:server:
    desc: Run server
    deps:
      - build:server
    cmds:
      - bin/server

  run:worker:
    desc: Run worker
    deps:
      - build:worker
    cmds:
      - bin/worker

  clean:
    desc: Clean build artifacts
    aliases: ["c"]
    cmds:
      - go clean
      - rm -rf bin
      - rm -rf .task

  test:
    desc: Run tests
    aliases: ["t"]
    cmds:
      - go test -v ./...

  ngrok:
    desc: Startup Ngrok
    cmds:
      - ngrok http --domain {{.NGROK_DOMAIN}} 8000

  docker:build:
    desc: Build docker images
    cmds:
      - task: docker:build:server
      - task: docker:build:worker

  docker:build:server:
    desc: Build CI server docker image
    cmds:
      - docker build --pull -f docker/Dockerfile.server -t {{.SERVER_IMAGE}}
        --build-arg CREATED="{{.DATETIME}}"
        --build-arg VERSION={{.VERSION}}
        --build-arg REVISION={{.REVISION}}
        .

  docker:build:worker:
    desc: Build worker docker image
    cmds:
      - docker build --pull -f docker/Dockerfile.worker -t {{.WORKER_IMAGE}}
        --build-arg CREATED="{{.DATETIME}}"
        --build-arg VERSION={{.VERSION}}
        --build-arg REVISION={{.REVISION}}
        .

  docker:compose:
    desc: Run docker-compose
    cmds:
      - docker compose -f docker/compose.yaml up

  migrate:create:
    desc: Create new migration file
    cmds:
      - migrate create -ext sql -dir sql/migrations -format 20060102150405 {{.CLI_ARGS}}

  migrate:up:
    desc: Run migrations up
    cmds:
      - migrate -path sql/migrations -database ${DB_URI} -verbose up

  migrate:down:
    desc: Run migrations down
    cmds:
      - migrate -path sql/migrations -database ${DB_URI} -verbose down

  generate:
    desc: Generate code
    cmds:
      - sqlc generate
      - protoc --go_out=. --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        internal/proto/pipeline_reporter.proto
