// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: service_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceUser = `-- name: CreateServiceUser :one
INSERT INTO public.service_user (service, username, email, access_token, refresh_token, token_type, token_expire, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateServiceUserParams struct {
	Service      Service
	Username     string
	Email        string
	AccessToken  string
	RefreshToken pgtype.Text
	TokenType    string
	TokenExpire  pgtype.Timestamp
	UserID       int64
}

func (q *Queries) CreateServiceUser(ctx context.Context, arg CreateServiceUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createServiceUser,
		arg.Service,
		arg.Username,
		arg.Email,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.TokenExpire,
		arg.UserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserID = `-- name: GetUserID :one
SELECT user_id
FROM public.service_user
WHERE service = $1 AND username = $2
`

type GetUserIDParams struct {
	Service  Service
	Username string
}

func (q *Queries) GetUserID(ctx context.Context, arg GetUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUserID, arg.Service, arg.Username)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}
