// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: service_user.sql

package db

import (
	"context"
)

const getServiceUserIDsByServiceUsername = `-- name: GetServiceUserIDsByServiceUsername :one
SELECT id, user_id
FROM public.service_user
WHERE username = $1 AND service = $2
`

type GetServiceUserIDsByServiceUsernameParams struct {
	Username string
	Service  Service
}

type GetServiceUserIDsByServiceUsernameRow struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetServiceUserIDsByServiceUsername(ctx context.Context, arg GetServiceUserIDsByServiceUsernameParams) (GetServiceUserIDsByServiceUsernameRow, error) {
	row := q.db.QueryRow(ctx, getServiceUserIDsByServiceUsername, arg.Username, arg.Service)
	var i GetServiceUserIDsByServiceUsernameRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
